### ISSUE TITLE
Ajouter les actions de contrôle de qualité du code

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-cadastre-module#12]
Comme pour lizmap-web-client, ajouter les actions : 

- [x] php-cs-fixer 
- [x] eslint
- [ ] phpstan

**Comment by Gustry** [comment]
Depuis le merge d'EsLint, l'action github est rouge @drillinP, un avis ?

**Comment by drillinP** [comment]
Toutes les erreurs non pas était corrigés

**Comment by Gustry** [comment]
Ok, mais je pense que l'objectif de l'action est de corriger pour que cela soit vert. Ou alors le dire dans le PR (car l'action ne tourne pas forcément tant que ce n'est pas dans la branche du dépôt principal)
