### ISSUE TITLE
Corriger les erreurs eslint

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-cadastre-module#17]
Suite #12 il faut corriger les erreurs trouvé par eslint.

**Comment by drillinP** [comment]
dans le lot de correction il y a plein de 'xhr, e, ui` es ce que dans certains il les faut ou on peut tous les virer ?

**Comment by rldhont** [comment]
Tout ce qui est défini mais jamais utilisé peut-être supprimé. Je suis convaincu que les `e` inutilisés le sont car ceux sont des paramètres de fonctions.

**Comment by drillinP** [comment]
très bien je m'en charge @rldhont

**Comment by Gustry** [comment]
On peut fermer ?
C'est dans #9

**Comment by rldhont** [comment]
Merci @Gustry
