### ISSUE TITLE
Configuration du module et du projet QGIS suite à l'installation

### ISSUE THREAD

**Issue by xavyeah39** [3liz/lizmap-cadastre-module#2]
Bonjour,
Une bonne année 2020 à toute l'équipe et un grand merci pour ce joli cadeau de noël !

Je me suis empressé de le déballer sur une instance Lizmap fonctionnelle (Debian 10 + PG11, QGIS Server 3.4.14 et LWC 3.3.3).
L'installation semble OK (rôle groupe et privilèges cadastre crées et RAS côté logs).

Cependant je ne comprend pas comment faire le lien entre un projet .qgs contenant les données cadastrales (tables importées depuis le plugin cadastre desktop via une BDD PostGIS) et le module dans Lizmap.
Mon projet se charge correctement dans LWC, l'utilisateur appartient bien au groupe `cadastre_lizmap`, le projet s'appelle `cadaste.qgs` mais le module ne semble pas actif.

Y-a-t'il des paramètres de configuration particuliers à appliquer pour spécifier un répertoire et un projet .qgs + .cfg cible afin d'activer le module ?

Merci d'avance pour vos lumières et pour ce chouette travail !

**Comment by rldhont** [comment]
Il faut utiliser l'algorithme de configuration du plugin cadastre. Le projet doit contenir des variables avec les identifiants des couches nécessaire au module : parcelles, sections, communes.

**Comment by xavyeah39** [comment]
Merci pour la réponse @rldhont !

J'ai pourtant bien utilisé l'utilitaire de chargement des données du plugin et j'ai bien les variables des 3 couches dans le projet :
![image](https://user-images.githubusercontent.com/16793813/78760084-ec923100-7980-11ea-8758-a30dcb345d4d.png)


Il est publié dans un répertoire sur lequel le groupe `cadastre_lizmap` a bien les droits mais je n'ai toujours rien côté interface ni côté logs.
Merci,

**Comment by rldhont** [comment]
Avez-vous installer le plugin cadastre pour QGIS Server ?

**Comment by xavyeah39** [comment]
Oui je l'ai installé par déduction mais n'ayant pas trouvé de documentation spécifique sur la partie serveur du plugin, j'ai improvisé un peu en suivant la même logique qu'avec d'autres plugin (comme WfsOutputExtension qui lui fonctionne sur mon instance) :  

* j'ai téléchargé l'archive du plugin cadastre (1.8.1) dans le répertoire `/opt/qgis-server/plugins`
* dézippé l'archive puis renommé le repertoire `QgisCadastrePlugin`
* redémarré apache (configuré avec fcgid comme expliqué dans la doc qgis-server)

Mais je passe probablement à côté de quelque chose...

**Comment by rldhont** [comment]
Le dossier du plugin doit-être cadastre.

Ensuite quand vous redémarrer vous devriez voir dans les logs de QGIS Server un message de chargement du plugin.

**Comment by xavyeah39** [comment]
Si près du but... Merci 1000 fois @rldhont !! 👍 
Effectivement, le service est bien présent dans les logs et le module actif dans LWC.
Plus qu'à tester tout ça. 

Et bravo à l'équipe pour toutes ces chouettes réalisations !
A bientôt,

**Comment by Gustry** [comment]
Je voulais garder ce ticket ouvert pour améliorer la documentation. Par exemple le nom du plugin côté serveur.
C'est mentionné où qu'il faut installer le plugin cadastre sur le serveur?

**Comment by Gustry** [comment]
Fixed 9492a2b

**Comment by xavyeah39** [comment]
Top ! Merci Etienne.
