### ISSUE TITLE
Le module a cessé de fonctionné (suite MAJ qgis-serveur ?)

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-cadastre-module#33]
J'ai un souci, le module cadastre a cessé de fonctionner du jour au lendemain la semaine dernière.
Ceci est peut-être dû à la mise à jour de Qgis server de ma version 3.16.1 à la version 3.16.7 ? Je ne peux pas en être sûr, les mises à jour du système étant faites automatiquement. Suite à ce problème, j'ai mis à jour Lizmap vers la version 3.4.3. J'ai également mis à jour le module cadastre. Le plugin Lizmap de Qgis est à jour également.

Je précise que je n'ai aucun souci avec le reste de l'application. Le plugin fonctionne également bien sous Qgis.

Les commandes du module Cadastre apparaissent bien dans LizMap, mais j'ai ce message d'erreur : "Erreur de création du relevé."

Direction les logs: 
`2021-06-14 11:48:30	192.168.0.124	warning	2021-06-14 11:48:30	[2]	file_get_contents(http://192.168.0.6/qgisserver/qgis_mapserv.fcgi?layer=Parcelles&amp;map=%2Fhome%2Fsig%2Fwebmapping%2Ddata%2Fprojets%2Feaux%2Feau%5Fassainissement%2Eqgs&amp;parcelle=7402250000E0367&amp;request=createPdf&amp;service=CADASTRE&amp;type=parcelle&amp;Lizmap%5FUser=BLoic&amp;Lizmap%5FUser%5FGroups=%5F%5Fpriv%5FBLoic%2C%20admins%2C%20cadastre%2C%20cadastre%5Flizmap%2C%20dechets%2C%20eau%5Fassainissement%2C%20eau%5Fassainissement%5Fedit%2C%20lizadmins%2C%20pluih%2C%20randonnee%2C%20social%2C%20transports%2C%20urbanisme%2C%20users%2C%20utilisateurs&amp;Lizmap%5FOverride%5FFilter=1): failed to open stream: HTTP request failed! HTTP/1.1 500
	/var/www/lizmap_3.4.3/lizmap/modules/lizmap/classes/lizmapProxy.class.php	249
`

`2021-06-14 11:48:30	192.168.0.124	notice	2021-06-14 11:48:30	[8]	Trying to get property 'status' of non-object	/var/www/lizmap_3.4.3/lizmap/lizmap-modules/cadastre/classes/lizmapCadastreRequest.class.php	123`

`2021-06-14 11:48:30	192.168.0.124	notice	2021-06-14 11:48:30	[8]	Trying to get property 'data' of non-object	/var/www/lizmap_3.4.3/lizmap/lizmap-modules/cadastre/controllers/service.classic.php	111`

`2021-06-14 11:48:30	192.168.0.124	notice	2021-06-14 11:48:30	[8]	Trying to get property 'tokens' of non-object	/var/www/lizmap_3.4.3/lizmap/lizmap-modules/cadastre/controllers/service.classic.php	111`

`2021-06-14 11:48:30	192.168.0.124	warning	2021-06-14 11:48:30	[2]	Invalid argument supplied for foreach()	/var/www/lizmap_3.4.3/lizmap/lizmap-modules/cadastre/controllers/service.classic.php	111`

**Comment by loic74** [comment]
Sorry. This was due to the fact that I had forgotten to update the cadastre plugin on the server, in addition to the module!

**Comment by Gustry** [comment]
C'est bon à savoir en effet.

Il faudrait que le module puisse vérifier la version qui tourne sur QGIS Serveur et avoir une matrice de compatibilité.
