### ISSUE TITLE
Les parcelles sélectionnées ne s'affichent pas

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-cadastre-module#68]
Bonjour,

J'ai préparé un projet QGIS en suivant strictement la documentation disponible ici : https://docs.3liz.org/QgisCadastrePlugin/module-lizmap/configuration/#dans-lizmap-web-client

Quand je le mets en ligne, si je sélectionne des parcelles, la sélection s'effectue bien ("X objets sélectionnés" s'affiche dans le panneau de Sélection) mais les parcelles sélectionnées ne changent pas de couleur sur la carte. Même constat si on rend les couches Sections ou Communes sélectionnables. Le problème pourrait-il venir d'un mauvais paramétrage du projet QGIS ? Ou de la configuration de l'infrastructure ? Si quelqu'un a une idée je suis preneuse.

Versions utilisées : 
- Qgis server : 3.22.6
- Qgis Desktop : 3.22.6
- PostgreSQL : 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
- PostGIS : 3.0
- extension cadastre QGIS Desktop : 1.14.2
- extension cadastre QGIS Server : Ne sais pas
- Lizmap Web Client : 3.5.2
- module cadastre Lizmap : Probablement 1.7.1 mais je ne peux pas le vérifier

**Comment by Gustry** [comment]
> extension cadastre QGIS Server : Ne sais pas
Lizmap Web Client : 3.5.2

Pour la première, dans votre interface d'administration de Lizmap, il faut aller dans l'onglet "Information serveur". C'est marqué.
Sinon, depuis l'extension QGIS bureautique Lizmap, un clic droit sur votre serveur, puis "afficher toutes les versions". Vous pouvez aussi copier/coller ici le résultat avec l'option juste en dessous.

LWc 3.5.2 est assez vieux justement votre problème est avec les noms courts et les versions récentes de LWC corrigent plusieurs soucis la-dessus.

Solution plus rapide, il faut supprimer les noms courts sur les couches, CF discussion https://github.com/3liz/lizmap-web-client/issues/2985

**Comment by Mavialle** [comment]
Bonjour,

Je n'avais pas vu le post #2985, je suis désolée. La suppression des noms courts à régler mon soucis, je vous en remercie, ça faisait des heures que je cherchais ! On est d'accord que pour l'instant le bug n'est pas encore réglé sur une version plus récente de LWc ?

Et concernant la première partie de votre message, je pense qu'il y a un truc à revoir dans notre installation car dans les informations serveur de l'admin Lizmap il y a marqué "Nous ne pouvons avoir les détails sur l'installation de votre serveur QGIS (version, extensions etc.). Soit la version installée du serveur QGIS est inférieure à 3.10, soit le plugin Lizmap n'est pas installé sur votre serveur, ou installé avec une version inférieur à 3.7.0. Mettez à jour QGIS Serveur au minimum à la version 3.10, et installez ou mettez à jour l'extension Lizmap à la version 3.7.0 minimum, en lisant la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html.".

Il y a donc quelque chose qui cloche, sûrement avec l'extension Lizmap. Merci d'avoir attiré mon attention à ce sujet.

Bonne journée !
