### ISSUE TITLE
Cannot install v2.0.3 on lizmap-web-client 3.6.5

### ISSUE THREAD

**Issue by jfoucher** [3liz/lizmap-cadastre-module#92]
Error is as follows : 
```
cd /var/www/html/lizmap/lizmap/install/ && php configurator.php cadastre:
0.476 Configuration is starting
0.477 [error] Unknown module cadastre
```
The cadastre module was installed with the following command : 
```
cd /var/www/html/lizmap/lizmap/my-packages/ && composer require "lizmap/lizmap-cadastre-module:2.0.3"
```

which ran without a hitch.

Anything I can do to help solve this issue ?

Thanks.

**Comment by Gustry** [comment]
Bonjour, merci pour le retour.
Pouvez-vous expliquer ce que vous avez pu faire pour corriger ?

Peut-être que d'autres utilisateurs vont tomber sur ce ticket avec la même manipulation initiale.

**Comment by jfoucher** [comment]
Rien de spécial, je lançais ça dans un Dockerfile au lieu du entrypoint. Ca n'aurait jamais marché dans un Dockerfile. Mais même après cela le module cadastre n'apparait jamais, aolrs qu'il est bien activé sur qgis server et que l'installation sur LWC se passe bien...
